version: '3.7'
networks:
  ingress:
    driver: bridge
services:
  api:
    container_name: 'bom-go-api'
    build:
        context: .
        dockerfile: ./Dockerfile
    volumes:
      - .:/app
    ports:
      - '8080:8080'
    restart: on-failure
    depends_on:
      - 'mongo'
    networks:
      - ingress
  mongo:
    container_name: 'bom-mongo-db'
    image: 'mongo:latest'
    volumes:
      - ./data/dev/mongo:/data/db
    ports:
      - '27100:27017'
    environment:
        - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
        - MONGO_INITDB_DATABASE=${MONGO_DBNAME}
        - MONGO_INITDB_DATA_PATH=/data/db
    restart: on-failure
    networks:
      - ingress