version: '3.3'
services:
  api:
    container_name: 'bom-go-api'
    image: 'bomtawep/bom-go-api:latest'
    volumes:
      - .:/app
    ports:
      - '8080:8080'
    restart: on-failure
    depends_on:
      - 'mongo'
  web:
    container_name: 'bom-nginx'
    image: 'bomtawep/bom-nginx:latest'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
    restart: on-failure
    depends_on:
      - 'api'
  mongo:
    container_name: 'bom-mongo-db'
    image: 'mongo:latest'
    volumes:
      - ./data/dev/mongo:/data/db
    ports:
      - '27100:27017'
    environment:
        - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
        - MONGO_INITDB_DATABASE=${MONGO_DBNAME}
        - MONGO_INITDB_DATA_PATH=/data/db
    restart: on-failure