name: CI

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t bom_proj_go .
          docker tag bom_proj_go bomtawep/bom_proj_go:latest
          docker push bomtawep/bom_proj_go:latest

      - name: Install SSH
        run: sudo apt-get install -y openssh-client

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_SSH_PRIVATE_KEY }}
          script: |
              docker pull bomtawep/mongo-db:latest
              docker stop bom_proj_go
              docker rm bom_proj_go
              docker run -d -p 8080:8080 --name bom_proj_go bomtawep/bom_proj_go:latest
