name: CI

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t mongo-db .
          docker tag mongo-db bomtawep/mongo-db:latest
          docker push bomtawep/mongo-db:latest

      - name: Install SSH
        run: sudo apt-get install -y openssh-client

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        run: sudo ssh -i "bom.pem" ec2-user@ec2-54-255-227-26.ap-southeast-1.compute.amazonaws.com
        with:
          host: ec2-54-255-227-26.ap-southeast-1.compute.amazonaws.com
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull bomtawep/mongo-db:latest
            docker run -d -p 27100:27017 --name mongo-db bomtawep/mongo-db:latest