name: CI

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build API and push Docker image
        run: |
          docker build -t bom-go-api .
          docker tag bom-go-api bomtawep/bom-go-api:latest
          docker push bomtawep/bom-go-api:latest

      - name: Build Nginx and push Docker image
        run: |
          docker build -t nginx .
          docker tag nginx bomtawep/nginx:latest
          docker push bomtawep/nginx:latest

      - name: Install SSH
        run: sudo apt-get install -y openssh-client

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_SSH_PRIVATE_KEY }}
          script: |
            docker-compose -f docker-compose.yml up -d
            docker pull bomtawep/nginx:latest
            docker stop nginx
            docker rm nginx
            docker run -d -p 80:80 --name nginx bomtawep/nginx:latest