name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t mongo-db .
          docker tag mongo-db bomtawep/mongo-db:latest
          docker push bomtawep/mongo-db:latest

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AWS_EC2_SSH_PRIVATE_KEY }}

      - name: SSH into EC2 and pull Docker image
        run: |
          ssh -i "bom.pem" ec2-user@ec2-54-255-227-26.ap-southeast-1.compute.amazonaws.com 'docker pull bomtawep/mongo-db:latest'

#      - name: SSH into EC2 instance and pull Docker image
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.AWS_EC2_HOST }}
#          username: ${{ secrets.AWS_EC2_USERNAME }}
#          key: ${{ secrets.AWS_EC2_SSH_PRIVATE_KEY }}
#          script: |
#            docker login -u bomtawep -p ${{ secrets.DOCKER_PASSWORD }}
#            docker pull bomtawep/mongo-db:latest
#            docker run -d -p 80:80 bomtawep/mongo-db:latest
