name: CI

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build API and push Docker image
        run: |
          docker build -t bom-go-api .
          docker tag bom-go-api bomtawep/bom-go-api:latest
          docker push bomtawep/bom-go-api:latest

      - name: Build nginx and push Docker image
        run: |
          docker build -t bom-nginx ./nginx
          docker tag bom-nginx bomtawep/bom-nginx:latest
          docker push bomtawep/bom-nginx:latest

      - name: Install SSH
        run: sudo apt-get install -y openssh-client

      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_SSH_PRIVATE_KEY }}
          source: "./nginx/nginx.conf"
          target: "/etc/nginx/conf.d/default.conf"

      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_SSH_PRIVATE_KEY }}
          source: "docker-compose.production.yml"
          target: "~/docker-compose.yml"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_SSH_PRIVATE_KEY }}
          script: |
            docker-compose up -d